ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Solution Strategy

The GameY project follows a layered structured divided into UI, game logic and backend user handling

=== Technology decisions

* The UI will be develop using React, due to one of the members already knowing it; Vite and TypeScript due to constraints
* The logic will consist of a Rust application due to constraints
* The users will be handle by a MongoDB database because we believe it is a very powerful database and would be great to know for our careers.
* Github will be used as the cloud platform to work due to constraints
* Docker will be used to deploy the application due to constraints

=== Quality goals

Maintainability of the code is achieved through the architectural pattern chosen to split different sections of the project
Reliability again is achieved through the layered structure, as the persistence layer with the database ensures it
Security will be handled through strict user validation during the login
Usability will be achieved through the clear implementation of the user interface and a variety of options to choose from when playing

ifdef::arc42help[]
[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape system architecture. It includes

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the foundation for many other detailed decisions or implementation rules.

.Form
Keep the explanations of such key decisions short.

Motivate what was decided and why it was decided that way,
based upon problem statement, quality goals and key constraints.
Refer to details in the following sections.


.Further Information

See https://docs.arc42.org/section-4/[Solution Strategy] in the arc42 documentation.

****
endif::arc42help[]
